### PR TITLE
Create SravanKGhantasala.md

### PR DESCRIPTION
**Pull request by sravankghantasala**
Created as a part of training!

### CODE REVIEW

**Comment by PeterBell** [comment]
I think this is great :+1: let's :ship: it

**Comment by ilansmith** [comment]
Looks good to me :+1.

**Comment by microroo** [comment]
+1

**Comment by DivyaRaju8689** [comment]
Good Job

**Comment by harishkothuri** [comment]
Great :+1:

**Comment by PeterBell** [comment]
Hey @crichid would you mind giving me your thoughts on this PR

**Comment by crichID** [comment]
@PeterBell looks great to me :shipit:

**Pull request merged**
